### ISSUE TITLE
links to compilers in the README

### ISSUE THREAD

**Issue by lheagy** [zhangning737/Drbsp#1]
(related to openjournals/joss-reviews#1328)

Are there links or recommendations you can provide as to how to obtain the compilers necessary to compile the code?

**Comment by zhangning737** [comment]
@lheagy OK, I'll update a link, and introduce how to get a community version of intel complier.

**Comment by zhangning737** [comment]
@lheagy commit 34c9ff6 Update readme.MD and documentation with hyperlink to open accessed intel parallel studio. Pls check it. Considering to add an option for gcc in future, declaration of external fortran function has a little difference with current compiler.
