### ISSUE TITLE
Compiling rdbsp throws errors

### ISSUE THREAD

**Issue by srmnitc** [zhangning737/Drbsp#2]
After installation of Intel Parallel studio , when ``rdbsp`` is compiled with ``Make -f Makefile_LINUX64``, it throws an error. See the attached image for the compiler message. Could be a problem with the specific setup, but in that case, more explanation in the installation section is required.
![hhh](https://user-images.githubusercontent.com/12624457/60393957-40800780-9b1d-11e9-8d56-0b9b1d7d9972.png)

**Comment by zhangning737** [comment]
@srmnitc found the problem, it should be induced by intel compiler configuration, please try to run
```
source /opt/intel/<compilers_and_libraries_version>/linux/bin/compilervars.sh intel64
```
before running
```
make -f Makefile_LINUX64
```
it will automatically configure the LD_LIBRARY_PATH to let the linker know when the libs.
Would mind get a try.
If anything wrong, pls let me know. Thanks.

**Comment by srmnitc** [comment]
@zhangning737 Will give it a try soon and tell you. Please add to documentation too!

**Comment by zhangning737** [comment]
@srmnitc OK, already update in the documentation and README.md...

**Comment by srmnitc** [comment]
The path you mentioned is not correct in my case, but I could find the path and everything works now.
I am just leaving the issue open so that you can document the instructions slightly better.

**Comment by zhangning737** [comment]
@srmnitc The path might different for different version, trying to make the docs more clear, not induce misunderstanding...
